[jupiter.server.http]
    port = 9099
[jupiter.etcdv3.default]
    endpoints=["etcd-naming.dz11.com:2379"]
    secure = false
[jupiter.registry.wh]
    configKey="jupiter.etcdv3.default"
    timeout = "1s"
[jupiter.logger.default]
    debug = false  # 是否在命令行输出
    enableConsole = false # 是否按命令行格式输出
    name = "default.json"
    dir = "."
[jupiter.trace.jaeger]
endpoint="http://localhost:14268/api/traces"
sample=1
