version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    labels:
      - dependencies
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /test/e2e
    labels:
      - dependencies
    schedule:
      interval: daily

  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - dependencies
    schedule:
      interval: "daily"
