package service

import (
	"context"
	"fmt"
	"github.com/bwmarrin/snowflake"
	"github.com/google/uuid"
	"github.com/google/wire"
	"sync"
	"uuid/gen/api/go/uuid/v1"
	"uuid/internal/pkg/grpc"
)

var ProviderSet = wire.NewSet(
	NewUuidService,
	wire.Struct(new(Options), "*"),
	grpc.ProviderSet,
)

// Options wireservice
type Options struct {
	UuidGrpc grpc.UuidInterface
	// ExampleMysql mysql.ExampleInterface
	// ExampleRedis redis.ExampleInterface
}

type Uuid struct {
	// snowflake Generated by default, nodeId cannot exceed 1023, and 0 ID is not used.
	// The uuid generator corresponding to the global node
	snowflakeRw  *sync.RWMutex
	snowflakeMap map[int16]*snowflake.Node
	Options
}

// NewUuidService 创建uuid服务
func NewUuidService(options Options) *Uuid {
	return &Uuid{
		snowflakeRw:  &sync.RWMutex{},
		snowflakeMap: make(map[int16]*snowflake.Node, 0),
		Options:      options,
	}
}

func (u *Uuid) GetUuidBySnowflake(ctx context.Context, req *uuidv1.GetUuidBySnowflakeRequest) (*uuidv1.GetUuidBySnowflakeRequestResponse, error) {
	nodeId := req.GetNodeId()
	if req == nil || nodeId <= 0 || nodeId > 1023 {
		return nil, fmt.Errorf("the requested parameter is invalid")
	}

	u.snowflakeRw.RLock()
	node, ok := u.snowflakeMap[int16(nodeId)]
	u.snowflakeRw.RUnlock()
	if !ok {
		var err error
		// Create a new Node with a Node number of nodeId
		node, err = snowflake.NewNode(int64(nodeId))
		if err != nil {
			return nil, fmt.Errorf("snowflake NewNode err:%v", err)
		}

		u.snowflakeRw.Lock()
		u.snowflakeMap[int16(nodeId)] = node
		u.snowflakeRw.Unlock()
	}

	// Generate a snowflake ID.
	id := node.Generate()

	return &uuidv1.GetUuidBySnowflakeRequestResponse{
		Uuid: id.String(),
	}, nil
}

func (u *Uuid) GetUuidByGoogleUUIDV4(ctx context.Context, req *uuidv1.GetUuidByGoogleUUIDV4Request) (*uuidv1.GetUuidByGoogleUUIDV4Response, error) {
	return &uuidv1.GetUuidByGoogleUUIDV4Response{Uuid: uuid.New().String()}, nil
}
