// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

import (
	"uuid/internal/pkg/grpc"
)

// Injectors from wire.go:

func createMockUuidService() *Uuid {
	uuidInterface := grpc.NewUuid()
	options := Options{
		UuidGrpc: uuidInterface,
	}
	uuid := NewUuidService(options)
	return uuid
}
