project_name: jupiter
version: 2

builds:
- main: ./cmd/jupiter
  id: "jupiter"
  binary: jupiter
  goos:
    - linux
    - darwin
    - windows
  goarch: [amd64]

- main: ./cmd/protoc-gen-go-echo
  id: "protoc-gen-go-echo"
  binary: protoc-gen-go-echo
  goos:
    - linux
    - darwin
    - windows
  goarch: [amd64]

- main: ./cmd/protoc-gen-go-gin
  id: "protoc-gen-go-gin"
  binary: protoc-gen-go-gin
  goos:
    - linux
    - darwin
    - windows
  goarch: [amd64]

- main: ./cmd/protoc-gen-go-xerror
  id: "protoc-gen-go-xerror"
  binary: protoc-gen-go-xerror
  goos:
    - linux
    - darwin
    - windows
  goarch: [amd64]

- main: ./cmd/protoc-gen-go-xfieldmask
  id: "protoc-gen-go-xfieldmask"
  binary: protoc-gen-go-xfieldmask
  goos:
    - linux
    - darwin
    - windows
  goarch: [amd64]

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch