// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

// Injectors from wire.go:

func createMockUuidService() *Uuid {
	options := Options{}
	uuid := NewUuidService(options)
	return uuid
}
