// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/douyu/jupiter/pkg/application"
	"uuid/internal/pkg/grpc"
	"uuid/internal/uuidserver/controller"
	"uuid/internal/uuidserver/service"
)

// Injectors from wire.go:

func InitApp(app *application.Application) error {
	uuidInterface := grpc.NewUuid()
	options := service.Options{
		UuidGrpc: uuidInterface,
	}
	uuid := service.NewUuidService(options)
	uuidHTTP := controller.NewUuidHTTPController(uuid)
	controllerOptions := controller.Options{
		UuidHTTP: uuidHTTP,
	}
	httpServer := NewHttpServer(controllerOptions)
	grpcServer := NewGrpcServer(uuid)
	serverOptions := Options{
		http: httpServer,
		grpc: grpcServer,
	}
	error2 := initApp(app, serverOptions)
	return error2
}
