[jupiter.server.http]
    port = 20105
[jupiter.server.grpc]
    port = 20102
    
[jupiter.cron.demo]
    immediatelyRun = true
    concurrentDelay = -1

[jupiter.grpc.default]
    configKey="jupiter.etcdv3.default"

[jupiter.logger.default]
    level = "info"
    debug = true

[jupiter.trace.jaeger]
    enableRPCMetrics = false
    [jupiter.trace.jaeger.sampler]
        type = "const"
        param = 0.001

[jupiter.reliability.sentinel]
    appName = "demo"