[jupiter.server.grpc]
port = 9092

[jupiter.registry.wh]
configKey = "jupiter.etcdv3.default"
timeout = "1s"

[jupiter.etcdv3.default]
connectTimeout = "10s"
endpoints = ["localhost:2379"]
secure = false