// Code generated by struct2interface; DO NOT EDIT.

package grpc

import (
	"context"
)

// UuidInterface ...
//
type UuidInterface interface {
	GetUuidBySnowflake(ctx context.Context) error
	GetUuidByGoogleUUIDV4(ctx context.Context) error
}
