// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/douyu/jupiter/pkg/application"
	"uuid/internal/app/uuidserver/controller"
	"uuid/internal/app/uuidserver/service"
	"uuid/internal/pkg/redis"
)

// Injectors from wire.go:

func InitApp(app *application.Application) error {
	redisRedis := redis.NewRedis()
	options := service.Options{
		Redis: redisRedis,
	}
	uuid := service.NewUuidService(options)
	uuidHTTP := controller.NewUuidHTTPController(uuid)
	uuidGrpc := controller.NewUUuidGrpcController(uuid)
	controllerOptions := controller.Options{
		UuidHTTP: uuidHTTP,
		UuidGrpc: uuidGrpc,
	}
	httpServer := NewHttpServer(controllerOptions)
	grpcServer := NewGrpcServer(controllerOptions)
	serverOptions := Options{
		http: httpServer,
		grpc: grpcServer,
	}
	error2 := initApp(app, serverOptions)
	return error2
}
