// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package e2e

import (
	"uuid/internal/app/uuidserver/service"
	"uuid/internal/pkg/redis"
)

// Injectors from wire.go:

func CreateUuidService() *service.Uuid {
	redisRedis := redis.NewRedis()
	options := service.Options{
		Redis: redisRedis,
	}
	uuid := service.NewUuidService(options)
	return uuid
}
