// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package e2e

import (
	"uuid/internal/uuidserver/service"
)

// Injectors from wire.go:

func CreateUuidService() *service.Uuid {
	options := service.Options{}
	uuid := service.NewUuidService(options)
	return uuid
}
